### PR TITLE
convert from klayjs to elkjs

### LINKED ISSUE #9: Convert from klayjs to elkjs
Elkjs is the newer version of klayjs, at some point it would be good to convert to using that.

### PR DESCRIPTION
**Pull request by nturley**
Fixes #9 
There might be some subtle breakage that I haven't noticed yet.

### CODE REVIEW

**Comment by nturley** [comment]
Elk did a very different looking layout on up3down5. I think the priority properties are maybe broken?

elklayout

**Comment by nturley** [comment]
priority is fixed, looks a little squashed now, but adjusting the spacing parameters in the skin should fix that. You can also see the problems from #15 

elklayout

**Comment by kasbah** [comment]
Just out of interest: what's up with the shim?

**Comment by nturley** [comment]
Maybe i'm doing things wrong, but it looks like `require(elkjs)` fails in browserify because it uses webworker-threads. klayjs didn't have that. It looks like elkjs made two versions, a nodejs version (`main.js`) and a browser version (`elkjs.bundled.js`). Looking at their package.json file, it looks like they ignore some of their web worker stuff when they invoke browserify for the browser version. So I figured I'd just use their browser version and ignore elkjs in my browserify call, which succeeded but the browser version exposed it's functionality through a global. The browserify handbook suggested using browserify-shim, and so I tried to follow the instructions for that, but it looks like now there's a versioning problem. For some reason nodejs 5 and 6 work, but nodejs 4 is unhappy. Something about a peer dependency version.

I'm considering just turning off nodejs 4 and only claiming support for 5 and 6 to make this problem go away, but I wish I understood what is going wrong better.

**Comment by nturley** [comment]
This introduced #25. I should've noticed it before I merged it to master.

**Pull request merged**
