### PR TITLE
Improve analog skin.

### PR DESCRIPTION
**Pull request by dvc94ch**
Adds a python test script for generating skin tests

screenshot from 2018-01-09 18-24-44
screenshot from 2018-01-09 18-24-50

### CODE REVIEW

**Comment by kasbah** [comment]
These look quite nice. The fact that the component outlines are thicker than the wires works quite well I think. 

There's conflicts between this and what's on master that need to be resolved. Also, the examples in `examples/analog` need to be updated.

**Comment by dvc94ch** [comment]
Making progress:
screenshot from 2018-01-10 12-17-47

**Comment by kasbah** [comment]
Nice, on second thought it might be better to have all the outlines/wires the same thickness. It looks a bit odd as the schematics scale up.

**Comment by nturley** [comment]
When you connect two horizontal ports, you'll get zigzags still. But if you add `s:dir="lateral"` to your horizontal ports, it will eliminate zig zags when you have a horizontal port connected to one or more vertical ports.
screen shot 2018-01-10 at 5 59 59 am

**Comment by dvc94ch** [comment]
This one is much harder to port swap. It detects the orientation correctly since it's connected from a signal net to a signal net.

Can the feedback path be improved?
screenshot from 2018-01-10 12-59-51

**Comment by nturley** [comment]
> This one is much harder to port swap

This goes into #31 bucket

>Can the feedback path be improved?

Something weird is happening there. It's missing the junction points as well. I'll try to reproduce.

**Comment by nturley** [comment]
Merged it, updated examples, and tagged lateral ports. Lateral port tagging improves most layouts but it makes a few cases a little worse. The examples all look better IMO.

**Pull request merged**
