### PR TITLE
Enable browser usage and add a basic demo

### PR DESCRIPTION
**Pull request by kasbah**
Adresses #10 and also adds a [basic demo](https://kasbah.github.io/netlistsvg/). 

The async style could be a lot nicer if:
- we change the `render` function to accept `Stream`s (e.g. `fs.createReadStream`) as well as Objects/Strings
- we adopt ES6 and return a Promise

It would also be nice to just bake the skin SVGs into the JS module somehow and then offer them as an option on the main render function. 

So, I'd **like to** adapt `lib.render` to be the following, **let me know what you think about this**:

### netlistsvg.render(input, [options]) : `Promise<String>`

| Param     | Type                      | Description                                                                                                                      |
| ---       | ---                       | ---                                                                                                                              |
| input    | `String`\|`Object`\|`ReadableStream` | JSON String, JS Object or ReadableStream from a JSON file                                                                                                       |
| [options] | `Object`    | Optional options, includes `{skin: null\|'default'\|'analog'\|<svg>}`

### CODE REVIEW

**Comment by kasbah** [comment]
I added a commit to start using [json5](https://github.com/json5/json5) to address #16 and added a formatting button to the [demo](https://kasbah.github.io/netlistsvg/).

**Comment by nturley** [comment]
You are faster than me, I just finished working on #10, and you already did all of this. I'll back out my change and merge this one instead.

**Comment by kasbah** [comment]
Ah, shame about the doubled effort. What do you think about moving to ES6/Promises and also of making use of ReadableStream?

**Comment by nturley** [comment]
All of it sounds great to me. I don't want to maintain XML as a giant javascript string, but if it gets generated at build time, then that should be fine.

**Comment by kasbah** [comment]
Thanks for merging, I'll open an issue for the ES6 and ReadableStream stuff. 

By the way, you should now be able to deploy to https://nturley.github.io/netlistsvg by doing the demo build (`npm run build-demo`) and pushing that to to a gh-pages branch (`git checkout -b gh-pages && git commit bundle.js index.html && git push -u origin gh-pages`). 

You can also give Travis CI a key and set it up to do that on every commit which might be useful

**Comment by nturley** [comment]
okay, that was way too hard. But I think I finally got it. Travis builds should be keeping the gh-pages branch up to date now.

**Pull request merged**
