### PR TITLE
Update ELKjs to latest version

### PR DESCRIPTION
**Pull request by nobodywasishere**
## Changes

- This is a fix for #105, bringing in a lot of improvements that have been made to the ELK layout engine since version 0.3.0.
- This updates yargs, jest, and ts-jest to the latest due to a vulnerability in yargs (more information [here](https://www.npmjs.com/advisories/1500))

## Testing

- Running `npm test` returns successfully, though you may have to clear the jest cache for this to work (coming from old versions of jest)
```
$ npm test

> netlistsvg@1.0.2 test
> npm run -s test-examples && npm run -s lint && jest

 PASS  test/drawModule.test.ts
 PASS  test/Cell.test.ts
 PASS  test/FlatModule.test.ts

Test Suites: 3 passed, 3 total
Tests:       9 passed, 9 total
Snapshots:   0 total
Time:        2.746 s, estimated 3 s
Ran all test suites.
```
- Properly rendered JSON in #105

### CODE REVIEW

**Comment by nturley** [comment]
I wanna merge this but why did it fail CI?

**Comment by nobodywasishere** [comment]
It's probably because it's going off of node 6 and Ubuntu 14.04, where node 10 has actually gone EOL this year. I'm currently in the process of updating the dependencies one by one locally and testing them, fixing issues as they appear, and I'm going to push to this branch with those changes.

**Comment by nobodywasishere** [comment]
It went with the `.travis.yml` currently in master instead of the one in the branch, which makes sense but means it'll fail. `yargs` specifically, only supports the [currently supported](https://nodejs.org/en/about/releases/) node versions.

The only packages I had trouble updating were Typescript (any version above 4.0.0) and replacing tslint with eslint. Everything else updated smoothly.

**Comment by nobodywasishere** [comment]
To make this simple, I'm going to leave this PR at only updating the ELKjs version and do the other updates in another PR, if that's okay.

**Pull request merged**
