### PR TITLE
Improve analog/mixed-signal handling and add examples

### PR DESCRIPTION
**Pull request by kasbah**
I managed to solve my issue from #6 by reading what you said before properly 😆 and detecting whether the analog skin is used, it's a bit of a hack but can be cleaned up along with the things I suggested in #19.  

This is based on #19 to avoid conflicts. 

I suppose we should be calling this "mixed signal" rather than "analog". Anyway, here is transistor!

### CODE REVIEW

**Comment by kasbah** [comment]
I rebased this against the master. Also, I moved the options for skipping of the `addConstants` and `addSplitsJoins` stages into the the skin itself.

**Comment by nturley** [comment]
Before, the skin file could define any properties and they would be passed through to the layout engine. Now only three properties are passed through. I think we should put our properties and layout properties in separate nodes.

maybe like this?
```XML
<s:properties
  constants="false"
  splitsAndJoins="false"
  <s:low_priority_alias val="$dff" />
  <s:layoutEngine
    spacing="20"
    borderSpacing="50"
    borderSpacing="50"
    direction="DOWN"/>
</s:properties>
```

**Comment by nturley** [comment]
I have good news and bad news. The bad news is that elk layered layout doesn't support hyper edges. Meaning that you can't have more than one string in a "sources" or "targets" list. If you do, it throws

`org.eclipse.elk.core.UnsupportedGraphException: Hyperedges are not supported.`

The workaround in klay was to create an edge from the source to every target. And it appears that the workaround still works, you can create an edge from every source to every target.

So this can be used for the multiple sources case, but it doesn't help us with the zero targets or the zero sources case. I think the solution to that case would be to create invisible dummy nodes to use as a source or as a target.

elklayout

Input edges
```json
"edges": [
    {
      "id": "e0",
      "sources": [
        "inthing.Y"
      ],
      "targets": [
        "outthing.A"
      ]
    },
    {
      "id": "e1",
      "sources": [
        "inthing2.Y"
      ],
      "targets": [
        "outthing.A"
      ]
    },
    {
      "id": "e2",
      "sources": [
        "inthing.Y"
      ],
      "targets": [
        "outthing2.A"
      ]
    },
    {
      "id": "e3",
      "sources": [
        "inthing2.Y"
      ],
      "targets": [
        "outthing2.A"
      ]
    }
  ]
```
Output edges
```json
"edges": [
    {
      "id": "e0",
      "sources": [
        "inthing.Y"
      ],
      "targets": [
        "outthing.A"
      ],
      "sections": [
        {
          "id": "e0_s0",
          "startPoint": {
            "x": 41,
            "y": 26.5
          },
          "endPoint": {
            "x": 86,
            "y": 26.5
          }
        }
      ]
    },
    {
      "id": "e1",
      "sources": [
        "inthing2.Y"
      ],
      "targets": [
        "outthing.A"
      ],
      "sections": [
        {
          "id": "e1_s0",
          "startPoint": {
            "x": 41,
            "y": 70.5
          },
          "endPoint": {
            "x": 86,
            "y": 26.5
          },
          "bendPoints": [
            {
              "x": 76,
              "y": 70.5
            },
            {
              "x": 76,
              "y": 26.5
            }
          ]
        }
      ]
    },
    {
      "id": "e2",
      "sources": [
        "inthing.Y"
      ],
      "targets": [
        "outthing2.A"
      ],
      "sections": [
        {
          "id": "e2_s0",
          "startPoint": {
            "x": 41,
            "y": 26.5
          },
          "endPoint": {
            "x": 86,
            "y": 70.5
          },
          "bendPoints": [
            {
              "x": 76,
              "y": 26.5
            },
            {
              "x": 76,
              "y": 70.5
            }
          ]
        }
      ],
      "junctionPoints": [
        {
          "x": 76,
          "y": 26.5
        },
        {
          "x": 76,
          "y": 70.5
        }
      ]
    },
    {
      "id": "e3",
      "sources": [
        "inthing2.Y"
      ],
      "targets": [
        "outthing2.A"
      ],
      "sections": [
        {
          "id": "e3_s0",
          "startPoint": {
            "x": 41,
            "y": 70.5
          },
          "endPoint": {
            "x": 86,
            "y": 70.5
          }
        }
      ]
    }
  ],
```

**Comment by kasbah** [comment]
I'll catch up with all of this after 34C3 but thought I would link in the recording of the talk I gave which mentions the work we have been doing on analog support for netlistsvg. I would have emailed you or something but I don't have any contact info. 

https://media.ccc.de/v/34c3-8818-designing_pcbs_with_code

**Comment by mithro** [comment]
@kasbah You are at 34c3? I am too! Come ask for Mithro at either the Failoverflow or OpenFPGA assemblies! Love to show you what I'm using netlistsvg for.

**Comment by kasbah** [comment]
I have rebased this against master. Regarding #25, I have just done the simplest thing for now. I don't really have any issue with having dots in properties and it seems more compact than the alternatives. 

The graphs generally look cleaner after the ELK upgrade (the wires join up better) but the vout wire is now too close to the transistor on the common emitter example.

**Comment by nturley** [comment]
I fixed the spacing issue [last night](https://github.com/nturley/netlistsvg/commit/d006fc24f52b6d400f50899016f596f5f6dfb0fc). Some of the spacing properties didn't work after the ELK migration, and it appears ELK compacts things a little more than KLAY did. But after I adjusted the ELK spacing properties, it looks better.

The wires joining up wasn't from the ELK migration, it was an issue that I fixed [last week](https://github.com/nturley/netlistsvg/commit/63d2dbdccbe6e284a1471999201cdb86661d1311) when I made ports 0x0 instead of 1x1.

Aaand, this is a little embarrassing but as I was working on hyper edges, I found out that you actually don't need to skip addConstants and split/join. It totally works fine. The REAL problems were in buildkgraph and createWires. And I fixed those [last week](https://github.com/nturley/netlistsvg/commit/2a3a4b87909f144d66cc5d2cda3e39542ad9c78c) as well.

So even on master right now, you can connect 2 outputs to 1 input. The dummies branch is supposed to fix the situation where you have 2 outputs to 0 inputs. It hasn't merged yet because I started talking to the ELK people about why some of my test cases looked weird (https://github.com/eclipse/elk/issues/276, https://github.com/eclipse/elk/issues/278). But I think that the best workaround at this point is to emulate undirected in-layer edges by creating an upstream dummy node. and use it as the source to target both ports, and not render the edge segments between the dummy and the first joint.

So, this won't cause any problems, but it turns out the skipping options are unnecessary. Sorry about that.

And the current rules as of now, are that every net needs at least one input and at least one output.

**Comment by kasbah** [comment]
Hmm, I tried applying your #12 fix for the analog skin but it didn't seem to help. Also, if I allow the "constants" operation I get this.

**Comment by kasbah** [comment]
>So this can be used for the multiple sources case, but it doesn't help us with the zero targets or the zero sources case. 

I guess I don't really understand why we would get zero sources or zero targets?

**Comment by nturley** [comment]
The old game I was trying to play was to strategically assign ports as inputs and outputs to avoid cases where you have zero sources and zero targets. But if you assign them wrong, it looks really bad.

The new game I am trying to play is that all downward ports are always considered sources and and upward ports are always considered targets and left and right ports should be targets to all sources in the net, and sources to all targets in the net. If you did this with your example, vout would be placed below the resistor and above the transistor, which would look more correct.

So, in the new game, there are some cases where we have multiple ports going upward or downward that are connected to each other and nothing else. Imagine a vertical capacitor between 3V3 and 5V. The two power supplies will have downward facing ports, and the vertical capacitor can only have one upward facing port so one of the nets will have two sources but zero targets.

I think in one of those examples with the weird constant behavior, you named a net "1". Don't do that. It's a yosys thing.

Using LONGEST_PATH coincidentally improves the horizontal spacing by splitting them up in different vertical layers. The better solution is to use elk.spacing.nodeNode. That should give you additional horizontal space between your nodes. Also verify that your transistor s:width is correct. ELK might think it has more space between them then it actually does.

**Comment by nturley** [comment]
yes, it looks like transistor `s:width` is smaller than it's actual width so ELK didn't know it was that wide.

**Comment by nturley** [comment]
> The new game I am trying to play is that all downward ports are always considered sources and and upward ports are always considered targets and left and right ports should be targets to all sources in the net, and sources to all targets in the net


This is what MCU looks like when you do it that way.

screen shot 2018-01-06 at 10 21 39 am

It adds additional vertical layers, but it reduces wire bends. The only tricky part is that currently neither our yosys json nor our skin defines which direction a port is pointing. It's inferred by the position (s:x, s:y). So to make this work properly, we'll need to add that information to the skin so we can look it up and make better decisions about which ports are sources and which are targets.

**Comment by kasbah** [comment]
Ah, I am starting to see what you are on about. That looks very nice.

**Comment by nturley** [comment]
Here are some fun examples I've been playing with

screen shot 2018-01-09 at 6 21 53 am


screen shot 2018-01-09 at 6 17 34 am

**Comment by kasbah** [comment]
Those look great, @dvc94ch has made some that don't look so good over on https://github.com/dvc94ch/pycircuit/issues/14#issuecomment-356094203.

**Comment by dvc94ch** [comment]
The reason they don't look so good is because pycircuit isn't generating the right port directions, that should be fixed soon.

Here's the skin I've been working on today:
screenshot from 2018-01-09 16-32-32

Is there a way to get the signal path to flow from left to right instead of zig-zaged? Also I think it would be nice to have the power ports connect to top and bottom on the generic component.

**Comment by nturley** [comment]
The zig zags are an artifact that I haven't been able to get rid of. I opened an issue on the layout engine about it https://github.com/eclipse/elk/issues/278. I don't think it's going to be addressed any time soon.

Fundamentally, we are trying to represent an undirected graph using a tool for laying out directed graphs. So the layered algorithm is a poor fit in some ways.

In theory, we could write our own layout algorithm that has this sort of 2 directional layering, but that would take some time.

**Pull request merged**
