### PR TITLE
Adding extra icons to default.svg

### PR DESCRIPTION
**Pull request by rjordans**
This change adds new icons for compares and some aliases for existing icons to improve rendering of Yosys generated diagrams.

### CODE REVIEW

**Comment by nicorikken** [comment]
@rjordans Nice to see a friend contributing :+1: Is netlist used in university?

**Comment by rjordans** [comment]
@mithro I'm not sure, it seems that there's more missing from the preview than just the added cells.

@nicorikken Ha, indeed nice to see you around here as well.  I've been using Yosys for some of my research and I'm starting to use netlistsvg for making nice figures for my slides now.  So far quite happy to see what it's doing already

**Comment by rjordans** [comment]
Here's an example output with some of the new nodes in use ($gt, $lt, $ge), for completeness this patch also adds $le.

netlist

Next to those new nodes I've also added $_DFF_P_ as alias for the dff, this makes it possible to also generate netlist figures after Yosys' synth command.  The DFF_P block is a positive-edge-triggered flip-flop, there is also a DFF_N in Yosys so we should probably add another symbol for that one as well.  I'm contemplating something with a 'not bubble' at the clock port to indicate the other clock edge there.

**Comment by rjordans** [comment]
@mithro regarding the visual diff, I think this may be because the default.svg file doesn't list a image or viewport size so the renderer picks some default size which only fits part of the image

**Comment by nturley** [comment]
Looks great! Thanks!

**Pull request merged**
